### ISSUE TITLE
First Time DigitalOcean Users

### ISSUE THREAD

**Issue by never00rei** [dustymabe/digitalocean-okd-install#1]
Hey, apologies for the issue but I found your repo from this article you wrote: https://dustymabe.com/2020/08/13/openshift-okd-on-fedora-coreos-on-digitalocean-part-1-deployment

This article/repo are very biased to users that have previous knowledge and experience of Digital Ocean, and as such it's not easy to get an instance stood up. So far my current problems have been:

You need to have at least one droplet stood up, tagged with the same cluster name you want to use in your OKD4 cluster otherwise you cannot use the firewall.

**Comment by dustymabe** [comment]
I'm not sure what problem you're hitting, but it shouldn't be required to have any droplets stood up before you run the script. The pre-requisites are mostly covered in https://dustymabe.com/2020/07/28/openshift-okd-on-fedora-coreos-on-digitalocean-part-0-preparation/

**Comment by dustymabe** [comment]
There is also a full demo/presentation of the whole process so maybe that could help answer some questions: https://dustymabe.com/2020/09/28/openshift-okd-on-fedora-coreos-on-digitalocean-part-4-recorded-demo/

**Comment by jkeam** [comment]
I think this is good to close?  @never00rei ?
