### ISSUE TITLE
Error when creating do-spaces

### ISSUE THREAD

**Issue by littleBinary** [dustymabe/digitalocean-okd-install#7]
When i run the script to deploy okd the following error happens:

make_bucket failed: s3://mycluster.mydomain An error occurred (XAmzContentSHA256Mismatch) when calling the CreateBucket operation: Unknown

If i create the bucket in the DO GUI to pass this error the script return just Bucket already exists... then the script is terminating..

make_bucket failed: s3://mycluster.mydomain An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: Bucket already exists

I couldnt see an error handling in your code for this case.  I also checked it out when i try to create the spaces with aws CLI. So the error comes from AWS CLI. 

aws --endpoint-url $SPACES_ENDPOINT s3 mb $SPACES_BUCKET
make_bucket failed: s3:// Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

A Fix for this issues would be nice.

#54~20.04.1-Ubuntu with:
AWS
DOCTL
OC
OPENSHIFT-INSTALL

**Comment by dustymabe** [comment]
If you try to run it manually like you are with `aws --endpoint-url $SPACES_ENDPOINT s3 mb $SPACES_BUCKET` you'll need to make sure the variables are defined. `Invalid bucket name ""` makes me thinkg `$SPACES_BUCKET` isn't defined.

**Comment by littleBinary** [comment]
Yea, i saw it later and tried it with defined variables but forgot to paste the error output. Its the same issue. What about to use a curl command to create the bucket instead of doctl?

**Comment by dustymabe** [comment]
> Yea, i saw it later and tried it with defined variables but forgot to paste the error output. Its the same issue. 

The same issue being "Invalid bucket name"? What bucket name are you trying to use? Does it pass the stated regex (`"^[a-zA-Z0-9.-_]{1,255}$"`)? 

> What about to use a curl command to create the bucket instead of doctl?

The AWS CLI is used to create the bucket, not `doctl`.

https://github.com/dustymabe/digitalocean-okd-install/blob/c620ac35171b5a42414a38efb201101908bdcd01/digitalocean-okd-install#L534

If you created the bucket using the GUI you could just comment out the make bucket call in the code so it gets skipped.
