### ISSUE TITLE
Doesn't work with newer version of okd 

### ISSUE THREAD

**Issue by stujb** [dustymabe/digitalocean-okd-install#8]
Trying to install okd 4.7 using this process on Digital Ocean. Had previously got it working with 4.4 but having loads of problems with 4.7 :(

It looks to me like the DNS setup is now different as the etcd specific records are not required and the installer relies on PTR records to configure etcd now. I seem to be having major conflicts between some etcd components using the control droplets' private ip and some using the public ip for the etcd configuration

Has anyone using this got it working on DO with okd 4.7 ?

**Comment by stujb** [comment]
An ongoing update on what I have discovered so far. It appears that the private IP's need PTR records for etcd to work.

Next steps are to standup a DNS server to host the private IP PTR records and figure out how make the droplets add that as nameserver at boot time

**Comment by stujb** [comment]
I managed to get this working on okd4.7 with etcd using droplet private ip addresses.

- Didn't need the PTR records for the private ips in the end
- Don't need the specific etcd DNS records anymore
- Had to set all DNS records for droplets to be the private rather than public IPs
- Did need to follow this doc https://github.com/openshift/okd/blob/4.7.0-0.okd-2021-05-22-050008/Guides/UPI/baremetal/nodes-custom-ip.md to get the nodes to use the private ip instead of public on the droplet
    - This was also out of date and needed to add `systemctl daemon-reload` to the end of the `okd-set-node-ip.sh` script. https://bugzilla.redhat.com/show_bug.cgi?id=1922812 [1]
- Had to add sshKey and machineNetwork details to the `resources/install-config.yaml.in` config file

[1] details of okd-set-node-ip.sh script
```
#!/bin/bash
HOSTNAME_RESOLVED_IP=""
while [[ ${HOSTNAME_RESOLVED_IP} == "" ]];
do
  HOSTNAME_RESOLVED_IP=$(nmcli connection show 'Wired connection 2' | grep IP4.ADDRESS | awk '{print $2}' | awk -F/ '{print $1}')
  echo "nmcli not available. sleeping..."
  sleep 2
done

echo "IP:${HOSTNAME_RESOLVED_IP}:"
printf "[Service]\nEnvironment=\"KUBELET_NODE_IP=${HOSTNAME_RESOLVED_IP}\"\n" > /etc/systemd/system/kubelet.service.d/20-nodenet.conf
printf "[Service]\nEnvironment=\"CONTAINER_STREAM_ADDRESS=${HOSTNAME_RESOLVED_IP}\"\n" > /etc/systemd/system/crio.service.d/20-nodenet.conf
printf "${HOSTNAME_RESOLVED_IP}" > /etc/hostname-resolved-ip
systemctl daemon-reload
```

- Needs the while loop as found that sometimes the script executed before NetworkManager was running and therefore nmcli was not returning IP
- The value written to /etc/hostname-resolved-ip is consumed on the bootstrap node only

**Comment by dustymabe** [comment]
Thanks @stujb for reporting your findings. I'll try to investigate soon. I haven't been using DO much lately and this has suffered as a result.

**Comment by stujb** [comment]
No problem

I am having some further issues when I try and lock down the outbound firewall rules. The droplets are unable to pull the user-data from 169.254.169.254 with a network unreachable error. 

Have raised a ticket with DO about it but as FCOS is not one of their supported images I'm not getting too far

**Comment by dustymabe** [comment]
I installed pushed some updates to the repo and got OKD 4.12 installed yesterday. The only issue I hit was https://github.com/okd-project/okd/issues/1607

I think I'll close this now, but feel free to re-open.
